twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'FormFields/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        stripe_public: '%env(STRIPE_PUBLIC)%'

when@test:
    twig:
        strict_variables: true
        debug: '%kernel.debug%'
